server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Application Custom Properties
security:
  keystore:
    alias: mytest
    filename: mytest.jks
    passphrase: mypass

oauth2:
  clientId: client-example
  clientSecret: client-secret
  scope: message-service